#

# LAB 00 - Curso de Pandas do Kaggle

site do curso: kaggle.com/learn/pandas

## Criar, ler e escrever

In [2]:
#pandas is a principal lib of data analysis with python.
import pandas as pd

### Dataframe is a table

In [8]:
dic = {
    'Yes': [50, 21],
    'No': [131, 2]
}
pd.DataFrame(dic)

   Yes   No
0   50  131
1   21    2

In [9]:
dic_with_string = {
    "Nike": ["Running shoes", "Football shoes", "Tennis shoes"],
    "Adidas": ["Running shoes", "Football shoes", "Tennis shoes"]
}
pd.DataFrame(dic_with_string)

dic_with_index = {
    "Nike": ["Running shoes", "Football shoes", "Tennis shoes"],
    "Adidas": ["Running shoes", "Football shoes", "Tennis shoes"]
}
pd.DataFrame(dic_with_index, index=["Model 1", "Model 2", "Model 3"])

                   Nike          Adidas
Model 1   Running shoes   Running shoes
Model 2  Football shoes  Football shoes
Model 3    Tennis shoes    Tennis shoes

### Series is a list

In [10]:
list_a = [1, 2, 3, 4, 5]
pd.Series(list_a)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
pd.Series(list_a, index=["a", "b", "c", "d", "e"], name="My Series")

a    1
b    2
c    3
d    4
e    5
Name: My Series, dtype: int64

### Exercise

In [4]:
#1. Create a DataFrame fruits
fruits = {
    "Banana": [5],
    "Orange": [10]
}
pd.DataFrame(fruits)

   Banana  Orange
0       5      10

In [10]:
#2. Create a DataFrame fruit_sales
fruit_sales = {
    "Banana": [5,15],
    "Orange": [10,20]
}
pd.DataFrame(fruit_sales, index=['2017 SALES', '2018 SALES'])

            Banana  Orange
2017 SALES       5      10
2018 SALES      15      20

In [13]:
#3. Create a series ingredients
list_ingredients = pd.Series(['2 spoon', '1 spoon'], index=['whey', 'milk'], name='Ingredients')
print(list_ingredients)

whey    2 spoon
milk    1 spoon
Name: Ingredients, dtype: str